#if !canImport(ObjectiveC)
import XCTest

extension S3StorageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__S3StorageTests = [
        ("testDelete", testDelete),
        ("testFetch", testFetch),
        ("testStore", testStore),
        ("testWrite", testWrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(S3StorageTests.__allTests__S3StorageTests),
    ]
}
#endif
